### ISSUE TITLE
Repair github action that publishes extension to chrome

### ISSUE THREAD

**Issue by dennyabrain** [tattle-made/Uli#387]
**Describe the bug**
The github action that we use for publishing the extension to chrome store is brittle. It breaks with the following error : 
```
< HTTP/1.1 100 Continue
} [16384 bytes data]
* We are completely uploaded and fine
* The requested URL returned error: 401 Unauthorized
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
} [2 bytes data]
curl: (22) The requested URL returned error: 401 Unauthorized
sh: FAILURE: unknown operand
```
Full logs can be read [here](https://github.com/tattle-made/Uli/actions/runs/5890758677/job/15976509040)
expand the "Upload to chrome" section

**To Reproduce**
This workflow has to be triggered manually by someone with write access to the repo. Contact @dennyabrain, @tarunima or @duggalsu 
It can be triggered by clicking "Run Workflow" on [this](https://github.com/tattle-made/Uli/actions/workflows/release-on-chrome.yml) page

**Expected behavior**
Successful completion of the workflow should upload a latest version of the plugin to the chrome store.

**Additional context**
The code for configuring the action is here : 
```
      - name: "Upload to chrome"
        uses: Klemensas/chrome-extension-upload-action@v1.3
        with:
          refresh-token: ${{ secrets.CHROME_STORE_REFRESH_TOKEN }}
          client-id: ${{ secrets.CHROME_STORE_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_STORE_CLIENT_SECRET }}
          file-name: "./browser-extension/plugin/extension.zip"
          app-id: "hbfmbflgailjeobfkhpdipcdmpclinki"
          publish: true
```
I am very certain this has to something with the refresh-token parameter. It makes sense that this works sometimes (when the token is active) and fails a week or two later (when the token is expired). But I can't figure out why such a brittle way of doing authentication is part of the action's official documentation. Either i misunderstood the auth flow or did it incorrectly. So in scope of this issue is investigating how to configure this action correctly and might involve reading up about google auth flows.
